# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fbc44b4d5bbefa77baf85831ba34b528e3a7b3f3fe30ce87b8a513f4f1a2633f2c7a45341d32c97fede3cae2fcb81e16f62dcc41311cc3f0f4e9597f5723bdf

test:
  secret_key_base: e2752410e98f7606def9aee983da5a907de9bf97e7a587bcdc2100c4e2fd22af9a4ecc9d8abde3ece1524112dc5db479e9db78b184d72ecd104e1c162b353f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
